openapi: 3.0.3
info:
  title: API Fleet Management - Taxis Company.
  description: |-
    API REST of a Fleet Managament Software to consult the location of the vehicles and their plates of a taxi company in Bejin, China. 
  
  version: 1.0.0
servers:
- url: http://127.0.0.1:8000/fleet-managment/api/taxis/?page=1

tags:
  - name: taxis
    description: This endpoint manages all the information related to the taxis, specifically the taxi ID and the plate.
paths:
  /taxis:
    get: 
      tags:
        - taxis
      summary: 'Obtiene información básica de los taxis paginados'
      parameters:
        - name: page
          in: query
          description: Número de página para la paginación (por defecto:1).
          required: false
          schema: 
            type: integer
            default: 1
      responses:
        '200':
          description: Éxito. Devuelve la información de los taxis.
          content:
            application/json:
              schema:
                type: object
                properties:
                  taxis:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: ID único del taxi.
                        plate:
                          type: string
                          description: Placa del taxi.