# Generated by Django 5.0.4 on 2024-04-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'taxis',
            },
        ),
        migrations.CreateModel(
            name='Trajectories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.taxis')),
            ],
            options={
                'verbose_name_plural': 'trajectories',
            },
        ),
    ]
